In [1]:
import pandas as pd
df = pd.read_csv("kerg.csv", sep=";", skiprows=5)

In [2]:
df

,Nr,Gebiet,gehört zu,Gewählt,Wahlberechtigte,Unnamed: 5,Unnamed: 6,Unnamed: 7,Wählende,Unnamed: 9,...,Unnamed: 131,WerteUnion,Unnamed: 133,Unnamed: 134,Unnamed: 135,Übrige,Unnamed: 137,Unnamed: 138,Unnamed: 139,Unnamed: 140
0,NaN,NaN,NaN,NaN,Erststimmen,NaN,Zweitstimmen,NaN,Erststimmen,NaN,...,NaN,Erststimmen,NaN,Zweitstimmen,NaN,Erststimmen,NaN,Zweitstimmen,NaN,NaN
1,NaN,NaN,NaN,NaN,Endgültig,Vorperiode,Endgültig,Vorperiode,Endgültig,Vorperiode,...,Vorperiode,Endgültig,Vorperiode,Endgültig,Vorperiode,Endgültig,Vorperiode,Endgültig,Vorperiode,NaN
2,1.0,Flensburg – Schleswig,1.0,–,232131,231536,232131,231536,192882,180112,...,NaN,NaN,NaN,NaN,NaN,471,384,NaN,563,NaN
3,2.0,Nordfriesland – Dithmarschen Nord,1.0,Christlich Demokratische Union Deutschlands,186019,188267,186019,188267,153755,145387,...,NaN,NaN,NaN,NaN,NaN,NaN,202,NaN,423,NaN
4,3.0,Steinburg – Dithmarschen Süd,1.0,Christlich Demokratische Union Deutschlands,175948,176899,175948,176899,146393,136299,...,NaN,NaN,NaN,NaN,NaN,NaN,795,NaN,630,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,298.0,St. Wendel,10.0,Christlich Demokratische Union Deutschlands,168073,173074,168073,173074,143181,139808,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,293,NaN
330,299.0,Homburg,10.0,Sozialdemokratische Partei Deutschlands,180479,185941,180479,185941,147979,142288,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,362,NaN
331,10.0,Saarland,99.0,NaN,734204,755223,734204,755223,605293,583963,...,NaN,NaN,NaN,NaN,NaN,NaN,299,NaN,1375,NaN
332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
333,99.0,Bundesgebiet,NaN,NaN,60510631,61172771,60510631,61172771,49928653,46707343,...,NaN,2849,NaN,6736,NaN,70163,180546,NaN,249620,NaN

Well, this is absolutely terrible.

In [3]:
df = df.dropna(how="all")

In [4]:
df

,Nr,Gebiet,gehört zu,Gewählt,Wahlberechtigte,Unnamed: 5,Unnamed: 6,Unnamed: 7,Wählende,Unnamed: 9,...,Unnamed: 131,WerteUnion,Unnamed: 133,Unnamed: 134,Unnamed: 135,Übrige,Unnamed: 137,Unnamed: 138,Unnamed: 139,Unnamed: 140
0,NaN,NaN,NaN,NaN,Erststimmen,NaN,Zweitstimmen,NaN,Erststimmen,NaN,...,NaN,Erststimmen,NaN,Zweitstimmen,NaN,Erststimmen,NaN,Zweitstimmen,NaN,NaN
1,NaN,NaN,NaN,NaN,Endgültig,Vorperiode,Endgültig,Vorperiode,Endgültig,Vorperiode,...,Vorperiode,Endgültig,Vorperiode,Endgültig,Vorperiode,Endgültig,Vorperiode,Endgültig,Vorperiode,NaN
2,1.0,Flensburg – Schleswig,1.0,–,232131,231536,232131,231536,192882,180112,...,NaN,NaN,NaN,NaN,NaN,471,384,NaN,563,NaN
3,2.0,Nordfriesland – Dithmarschen Nord,1.0,Christlich Demokratische Union Deutschlands,186019,188267,186019,188267,153755,145387,...,NaN,NaN,NaN,NaN,NaN,NaN,202,NaN,423,NaN
4,3.0,Steinburg – Dithmarschen Süd,1.0,Christlich Demokratische Union Deutschlands,175948,176899,175948,176899,146393,136299,...,NaN,NaN,NaN,NaN,NaN,NaN,795,NaN,630,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,297.0,Saarlouis,10.0,Christlich Demokratische Union Deutschlands,198307,203279,198307,203279,164765,159170,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,350,NaN
329,298.0,St. Wendel,10.0,Christlich Demokratische Union Deutschlands,168073,173074,168073,173074,143181,139808,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,293,NaN
330,299.0,Homburg,10.0,Sozialdemokratische Partei Deutschlands,180479,185941,180479,185941,147979,142288,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,362,NaN
331,10.0,Saarland,99.0,NaN,734204,755223,734204,755223,605293,583963,...,NaN,NaN,NaN,NaN,NaN,NaN,299,NaN,1375,NaN
333,99.0,Bundesgebiet,NaN,NaN,60510631,61172771,60510631,61172771,49928653,46707343,...,NaN,2849,NaN,6736,NaN,70163,180546,NaN,249620,NaN

In [5]:
df.describe

<bound method NDFrame.describe of         Nr                             Gebiet  gehört zu  \
0      NaN                                NaN        NaN
1      NaN                                NaN        NaN
2      1.0              Flensburg – Schleswig        1.0
3      2.0  Nordfriesland – Dithmarschen Nord        1.0
4      3.0       Steinburg – Dithmarschen Süd        1.0
..     ...                                ...        ...
328  297.0                          Saarlouis       10.0
329  298.0                         St. Wendel       10.0
330  299.0                            Homburg       10.0
331   10.0                           Saarland       99.0
333   99.0                       Bundesgebiet        NaN

                                         Gewählt Wahlberechtigte  Unnamed: 5  \
0                                            NaN     Erststimmen         NaN
1                                            NaN       Endgültig  Vorperiode
2                                              –          232131      231536
3    Christlich Demokratische Union Deutschlands          186019      188267
4    Christlich Demokratische Union Deutschlands          175948      176899
..                                           ...             ...         ...
328  Christlich Demokratische Union Deutschlands          198307      203279
329  Christlich Demokratische Union Deutschlands          168073      173074
330      Sozialdemokratische Partei Deutschlands          180479      185941
331                                          NaN          734204      755223
333                                          NaN        60510631    61172771

       Unnamed: 6  Unnamed: 7     Wählende  Unnamed: 9  ... Unnamed: 131  \
0    Zweitstimmen         NaN  Erststimmen         NaN  ...          NaN
1       Endgültig  Vorperiode    Endgültig  Vorperiode  ...   Vorperiode
2          232131      231536       192882      180112  ...          NaN
3          186019      188267       153755      145387  ...          NaN
4          175948      176899       146393      136299  ...          NaN
..            ...         ...          ...         ...  ...          ...
328        198307      203279       164765      159170  ...          NaN
329        168073      173074       143181      139808  ...          NaN
330        180479      185941       147979      142288  ...          NaN
331        734204      755223       605293      583963  ...          NaN
333      60510631    61172771     49928653    46707343  ...          NaN

      WerteUnion Unnamed: 133  Unnamed: 134 Unnamed: 135       Übrige  \
0    Erststimmen          NaN  Zweitstimmen          NaN  Erststimmen
1      Endgültig   Vorperiode     Endgültig   Vorperiode    Endgültig
2            NaN          NaN           NaN          NaN          471
3            NaN          NaN           NaN          NaN          NaN
4            NaN          NaN           NaN          NaN          NaN
..           ...          ...           ...          ...          ...
328          NaN          NaN           NaN          NaN          NaN
329          NaN          NaN           NaN          NaN          NaN
330          NaN          NaN           NaN          NaN          NaN
331          NaN          NaN           NaN          NaN          NaN
333         2849          NaN          6736          NaN        70163

    Unnamed: 137  Unnamed: 138 Unnamed: 139 Unnamed: 140
0            NaN  Zweitstimmen          NaN          NaN
1     Vorperiode     Endgültig   Vorperiode          NaN
2            384           NaN          563          NaN
3            202           NaN          423          NaN
4            795           NaN          630          NaN
..           ...           ...          ...          ...
328            0           NaN          350          NaN
329            0           NaN          293          NaN
330            0           NaN          362          NaN
331          299           NaN         1375          NaN
333       180546           NaN       249620          NaN

[318 rows x 141 columns]>

In [6]:
list(df.columns)

['Nr',
 'Gebiet',
 'gehört zu',
 'Gewählt',
 'Wahlberechtigte',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 'Wählende',
 'Unnamed: 9',
 'Unnamed: 10',
 'Unnamed: 11',
 'Ungültige Stimmen',
 'Unnamed: 13',
 'Unnamed: 14',
 'Unnamed: 15',
 'Gültige Stimmen',
 'Unnamed: 17',
 'Unnamed: 18',
 'Unnamed: 19',
 'Sozialdemokratische Partei Deutschlands',
 'Unnamed: 21',
 'Unnamed: 22',
 'Unnamed: 23',
 'Christlich Demokratische Union Deutschlands',
 'Unnamed: 25',
 'Unnamed: 26',
 'Unnamed: 27',
 'BÜNDNIS 90/DIE GRÜNEN',
 'Unnamed: 29',
 'Unnamed: 30',
 'Unnamed: 31',
 'Freie Demokratische Partei',
 'Unnamed: 33',
 'Unnamed: 34',
 'Unnamed: 35',
 'Alternative für Deutschland',
 'Unnamed: 37',
 'Unnamed: 38',
 'Unnamed: 39',
 'Christlich-Soziale Union in Bayern e.V.',
 'Unnamed: 41',
 'Unnamed: 42',
 'Unnamed: 43',
 'Die Linke',
 'Unnamed: 45',
 'Unnamed: 46',
 'Unnamed: 47',
 'FREIE WÄHLER',
 'Unnamed: 49',
 'Unnamed: 50',
 'Unnamed: 51',
 'PARTEI MENSCH UMWELT TIERSCHUTZ',
 'Unnamed: 53',
 'Unnamed: 54',
 'Unnamed: 55',
 'Basisdemokratische Partei Deutschland',
 'Unnamed: 57',
 'Unnamed: 58',
 'Unnamed: 59',
 'Partei für Arbeit, Rechtsstaat, Tierschutz, Elitenförderung und basisdemokratische Initiative',
 'Unnamed: 61',
 'Unnamed: 62',
 'Unnamed: 63',
 'Die Gerechtigkeitspartei – Team Todenhöfer',
 'Unnamed: 65',
 'Unnamed: 66',
 'Unnamed: 67',
 'Piratenpartei Deutschland',
 'Unnamed: 69',
 'Unnamed: 70',
 'Unnamed: 71',
 'Volt Deutschland',
 'Unnamed: 73',
 'Unnamed: 74',
 'Unnamed: 75',
 'Ökologisch-Demokratische Partei - Die Naturschutzpartei',
 'Unnamed: 77',
 'Unnamed: 78',
 'Unnamed: 79',
 'Südschleswigscher Wählerverband',
 'Unnamed: 81',
 'Unnamed: 82',
 'Unnamed: 83',
 'Partei für Verjüngungsforschung',
 'Unnamed: 85',
 'Unnamed: 86',
 'Unnamed: 87',
 'Partei der Humanisten - Fakten, Freiheit, Fortschritt',
 'Unnamed: 89',
 'Unnamed: 90',
 'Unnamed: 91',
 'Bündnis C - Christen für Deutschland',
 'Unnamed: 93',
 'Unnamed: 94',
 'Unnamed: 95',
 'Bayernpartei',
 'Unnamed: 97',
 'Unnamed: 98',
 'Unnamed: 99',
 'Marxistisch-Leninistische Partei Deutschlands',
 'Unnamed: 101',
 'Unnamed: 102',
 'Unnamed: 103',
 'Menschliche Welt - für das Wohl und Glücklichsein aller',
 'Unnamed: 105',
 'Unnamed: 106',
 'Unnamed: 107',
 'Partei des Fortschritts',
 'Unnamed: 109',
 'Unnamed: 110',
 'Unnamed: 111',
 'Sozialistische Gleichheitspartei, Vierte Internationale',
 'Unnamed: 113',
 'Unnamed: 114',
 'Unnamed: 115',
 'Bürgerrechtsbewegung Solidarität',
 'Unnamed: 117',
 'Unnamed: 118',
 'Unnamed: 119',
 'BÜNDNIS DEUTSCHLAND',
 'Unnamed: 121',
 'Unnamed: 122',
 'Unnamed: 123',
 'Bündnis Sahra Wagenknecht - Vernunft und Gerechtigkeit',
 'Unnamed: 125',
 'Unnamed: 126',
 'Unnamed: 127',
 'MERA25 - Gemeinsam für Europäische Unabhängigkeit',
 'Unnamed: 129',
 'Unnamed: 130',
 'Unnamed: 131',
 'WerteUnion',
 'Unnamed: 133',
 'Unnamed: 134',
 'Unnamed: 135',
 'Übrige',
 'Unnamed: 137',
 'Unnamed: 138',
 'Unnamed: 139',
 'Unnamed: 140']

In [7]:
df.columns[df.isin(['Zweitstimmen']).any()]

Index(['Unnamed: 6', 'Unnamed: 10', 'Unnamed: 14', 'Unnamed: 18',
       'Unnamed: 22', 'Unnamed: 26', 'Unnamed: 30', 'Unnamed: 34',
       'Unnamed: 38', 'Unnamed: 42', 'Unnamed: 46', 'Unnamed: 50',
       'Unnamed: 54', 'Unnamed: 58', 'Unnamed: 62', 'Unnamed: 66',
       'Unnamed: 70', 'Unnamed: 74', 'Unnamed: 78', 'Unnamed: 82',
       'Unnamed: 86', 'Unnamed: 90', 'Unnamed: 94', 'Unnamed: 98',
       'Unnamed: 102', 'Unnamed: 106', 'Unnamed: 110', 'Unnamed: 114',
       'Unnamed: 118', 'Unnamed: 122', 'Unnamed: 126', 'Unnamed: 130',
       'Unnamed: 134', 'Unnamed: 138'],
      dtype='object')

I want only the results for the AfD. In the German voting system, you get two votes: One for the direct candidate, one for the party. Since the AfD doesn't have a direct candidate in all districts and I think the second votes are generally more representative for party approval (there is often lots of tactics involved when choosing which direct candidate to vote for), I want only those. From checking the columns, I can tell that "Unnamed: 38" must be second votes for the AfD but I'm double-checking to be sure.

In [8]:
 df[['Alternative für Deutschland', 'Unnamed: 37', 'Unnamed: 38','Unnamed: 39']]

    Alternative für Deutschland Unnamed: 37   Unnamed: 38 Unnamed: 39
0                   Erststimmen         NaN  Zweitstimmen         NaN
1                     Endgültig  Vorperiode     Endgültig  Vorperiode
2                         28827        9768         29272       10317
3                         24474        8274         24564        8798
4                         29674       10429         29653       11303
..                          ...         ...           ...         ...
328                       35621       15111         35421       15651
329                       29038       12346         29391       12904
330                       34096       16210         34801       16068
331                      129177       56236        129294       57629
333                    10177318     4699926      10328780     4809233

[318 rows x 4 columns]

In [9]:
df = df[['Nr', 'Gebiet', 'Unnamed: 38']]

In [10]:
df

        Nr                             Gebiet   Unnamed: 38
0      NaN                                NaN  Zweitstimmen
1      NaN                                NaN     Endgültig
2      1.0              Flensburg – Schleswig         29272
3      2.0  Nordfriesland – Dithmarschen Nord         24564
4      3.0       Steinburg – Dithmarschen Süd         29653
..     ...                                ...           ...
328  297.0                          Saarlouis         35421
329  298.0                         St. Wendel         29391
330  299.0                            Homburg         34801
331   10.0                           Saarland        129294
333   99.0                       Bundesgebiet      10328780

[318 rows x 3 columns]

In [11]:
df = df.drop([0,1])

In [12]:
df = df.rename(columns={'Unnamed: 38': 'AfD Zweitstimmen'})

Getting rid of all the entries for entire states.

In [13]:
df[df['Gebiet'].str.contains('Baden-Württemberg|Bayern|Berlin|Brandenburg|Bremen|Hamburg|Hessen|Mecklenburg-Vorpommern|Niedersachsen|Nordrhein-Westfalen|Rheinland-Pfalz|Saarland|Sachsen|Sachsen-Anhalt|Schleswig-Holstein|Thüringen', na=False)]

       Nr                                             Gebiet AfD Zweitstimmen
13    1.0                                 Schleswig-Holstein           306165
21   13.0                             Mecklenburg-Vorpommern           357361
23   18.0                                      Hamburg-Mitte            19821
24   19.0                                     Hamburg-Altona            11602
25   20.0                                 Hamburg-Eimsbüttel            12524
26   21.0                                       Hamburg-Nord            15780
27   22.0                                   Hamburg-Wandsbek            25279
28   23.0                        Hamburg-Bergedorf – Harburg            28602
29    2.0                                            Hamburg           113608
61    3.0                                      Niedersachsen           894540
63   54.0                                           Bremen I            22793
64   55.0                            Bremen II – Bremerhaven            29703
65    4.0                                             Bremen            52496
71   60.0  Brandenburg an der Havel – Potsdam-Mittelmark ...            50225
77   12.0                                        Brandenburg           535275
87   15.0                                     Sachsen-Anhalt           496110
89   74.0                                       Berlin-Mitte            14291
90   75.0                                      Berlin-Pankow            31087
91   76.0                               Berlin-Reinickendorf            23124
92   77.0               Berlin-Spandau – Charlottenburg Nord            25305
93   78.0                         Berlin-Steglitz-Zehlendorf            18678
94   79.0                  Berlin-Charlottenburg-Wilmersdorf            14329
95   80.0                        Berlin-Tempelhof-Schöneberg            20986
96   81.0                                    Berlin-Neukölln            18874
97   82.0  Berlin-Friedrichshain-Kreuzberg – Prenzlauer B...            12986
98   83.0                            Berlin-Treptow-Köpenick            36410
99   84.0                         Berlin-Marzahn-Hellersdorf            46285
100  85.0                                 Berlin-Lichtenberg            34635
101  11.0                                             Berlin           296990
167   5.0                                Nordrhein-Westfalen          1770379
185  14.0                                            Sachsen           958401
209   6.0                                             Hessen           636778
219  16.0                                          Thüringen           510527
236   7.0                                    Rheinland-Pfalz           498695
285   9.0                                             Bayern          1515731
325   8.0                                  Baden-Württemberg          1256430
331  10.0                                           Saarland           129294

In [14]:
df = df.drop([13, 21, 29, 61, 65, 77, 87, 101, 167, 185, 209, 219, 236, 285, 325, 331])

In [15]:
df

        Nr                             Gebiet AfD Zweitstimmen
2      1.0              Flensburg – Schleswig            29272
3      2.0  Nordfriesland – Dithmarschen Nord            24564
4      3.0       Steinburg – Dithmarschen Süd            29653
5      4.0              Rendsburg-Eckernförde            27498
6      5.0                               Kiel            17884
..     ...                                ...              ...
327  296.0                        Saarbrücken            29681
328  297.0                          Saarlouis            35421
329  298.0                         St. Wendel            29391
330  299.0                            Homburg            34801
333   99.0                       Bundesgebiet         10328780

[300 rows x 3 columns]

And the one for all of Germany.

In [16]:
df = df.drop([333])

In [17]:
df.head()

    Nr                             Gebiet AfD Zweitstimmen
2  1.0              Flensburg – Schleswig            29272
3  2.0  Nordfriesland – Dithmarschen Nord            24564
4  3.0       Steinburg – Dithmarschen Süd            29653
5  4.0              Rendsburg-Eckernförde            27498
6  5.0                               Kiel            17884

In order to able to read this into QGIS, I have to clean up the data for the district number and add one more column that will make it possible to join it with the shapefile I have.

In [18]:
df.dtypes

Nr                  float64
Gebiet               object
AfD Zweitstimmen     object
dtype: object

In [20]:
df['Nr'] = df['Nr'].astype(int).astype(str).str.zfill(3)

In [21]:
df

      Nr                             Gebiet AfD Zweitstimmen
2    001              Flensburg – Schleswig            29272
3    002  Nordfriesland – Dithmarschen Nord            24564
4    003       Steinburg – Dithmarschen Süd            29653
5    004              Rendsburg-Eckernförde            27498
6    005                               Kiel            17884
..   ...                                ...              ...
324  295           Zollernalb – Sigmaringen            38796
327  296                        Saarbrücken            29681
328  297                          Saarlouis            35421
329  298                         St. Wendel            29391
330  299                            Homburg            34801

[299 rows x 3 columns]

In [22]:
df.to_csv('afd-results_clean.csv', index=False)